export const productSegments = [
  {
    src: "./navbar/pcmo.png",
    alt: "Passenger Car Motor Oils",
    title: "Passenger Car Motor Oils",
    link: "/products/passenger-car-motor-oils",
  },
  {
    src: "./navbar/gfeo.png",
    alt: "Gas Fuel Engine Oils",
    title: "Gas Fuel Engine Oils",
    link: "#",
  },
  {
    src: "./navbar/deo.png",
    alt: "Diesel Engine Oils",
    title: "Diesel Engine Oils",
    link: "#",
  },
  {
    src: "./navbar/tractor.png",
    alt: "Tractor Fluids",
    title: "Tractor Fluids",
    link: "#",
  },
  {
    src: "./navbar/4-stroke.png",
    alt: "Four-Stroke Motorcycle Oils",
    title: "Four-Stroke Motorcycle Oils",
    link: "#",
  },
  {
    src: "./navbar/2-stroke.png",
    alt: "Two-Stroke Motorcycle Oils",
    title: "Two-Stroke Motorcycle Oils",
    link: "#",
  },
  {
    src: "./navbar/marine.png",
    alt: "Marine & Large Engine Oils",
    title: "Marine & Large Engine Oils",
    link: "#",
  },
  {
    src: "./navbar/gear.png",
    alt: "Gear Oils",
    title: "Gear Oils",
    link: "#",
  },
  {
    src: "./navbar/transmission.png",
    alt: "Transmission Fluids",
    title: "Transmission Fluids",
    link: "#",
  },
  {
    src: "./navbar/industrial.png",
    alt: "Industrial Oils",
    title: "Industrial Oils",
    link: "#",
  },
  {
    src: "./navbar/transformer.png",
    alt: "Transformer & Electrical Oils",
    title: "Transformer & Electrical Oils",
    link: "#",
  },
  {
    src: "./navbar/specialty.png",
    alt: "Specialty Oils",
    title: "Specialty Oils",
    link: "#",
  },
  {
    src: "./navbar/brake.png",
    alt: "Brake Fluids",
    title: "Brake Fluids",
    link: "#",
  },
  {
    src: "./navbar/grease.png",
    alt: "Greases",
    title: "Greases",
    link: "#",
  },
];
