export const productSegments = [
  {
    src: "./navbar/pcmo.png",
    alt: "Passenger Car Motor Oils",
    title: "Passenger Car Motor Oils",
    link: "/products/passenger-car-motor-oils",
  },
  {
    src: "./navbar/gfeo.png",
    alt: "Gas Fuel Engine Oils",
    title: "Gas Fuel Engine Oils",
    link: "/products/gas-fuel-engine-oils",
  },
  {
    src: "./navbar/deo.png",
    alt: "Diesel Engine Oils",
    title: "Diesel Engine Oils",
    link: "/products/diesel-engine-oils",
  },
  {
    src: "./navbar/tractor.png",
    alt: "Tractor Fluids",
    title: "Tractor Fluids",
    link: "/products/tractor-fluids",
  },
  {
    src: "./navbar/4-stroke.png",
    alt: "Four-Stroke Motorcycle Oils",
    title: "Four-Stroke Motorcycle Oils",
    link: "/products/four-stroke-motorcycle-oils",
  },
  {
    src: "./navbar/2-stroke.png",
    alt: "Two-Stroke Motorcycle & Engine Oils",
    title: "Two-Stroke Motorcycle & Engine Oils",
    link: "/products/two-stroke-motorcycle-and-engine-oils",
  },
  {
    src: "./navbar/marine.png",
    alt: "Marine & Large Engine Oils",
    title: "Marine & Large Engine Oils",
    link: "/products/marine-and-large-engine-oils",
  },
  {
    src: "./navbar/gear.png",
    alt: "Gear Oils",
    title: "Gear Oils",
    link: "/products/gear-oils",
  },
  {
    src: "./navbar/transmission.png",
    alt: "Transmission Fluids",
    title: "Transmission Fluids",
    link: "/products/transmission-fluids",
  },
  {
    src: "./navbar/industrial.png",
    alt: "Industrial Oils",
    title: "Industrial Oils",
    link: "/products/industrial-oils",
  },
  {
    src: "./navbar/transformer.png",
    alt: "Transformer & Electrical Oils",
    title: "Transformer & Electrical Oils",
    link: "/products/transformer-and-electrical-oils",
  },
  {
    src: "./navbar/specialty.png",
    alt: "Specialty Oils",
    title: "Specialty Oils",
    link: "/products/specialty-oils",
  },
  {
    src: "./navbar/brake.png",
    alt: "Brake Fluids",
    title: "Brake Fluids",
    link: "/products/brake-fluids",
  },
  {
    src: "./navbar/grease.png",
    alt: "Greases",
    title: "Greases",
    link: "/products/greases",
  },
];
