export const productSegments = [
  {
    src: "./navbar/pcmo.webp",
    alt: "Passenger Car Motor Oils",
    title: "Passenger Car Motor Oils",
    link: "/products/passenger-car-motor-oils",
  },
  {
    src: "./navbar/gfeo.webp",
    alt: "Gas Fuel Engine Oils",
    title: "Gas Fuel Engine Oils",
    link: "/products/gas-fuel-engine-oils",
  },
  {
    src: "./navbar/deo.webp",
    alt: "Diesel Engine Oils",
    title: "Diesel Engine Oils",
    link: "/products/diesel-engine-oils",
  },
  {
    src: "./navbar/tractor.webp",
    alt: "Tractor Fluids",
    title: "Tractor Fluids",
    link: "/products/tractor-fluids",
  },
  {
    src: "./navbar/4-stroke.webp",
    alt: "Four-Stroke Motorcycle Oils",
    title: "Four-Stroke Motorcycle Oils",
    link: "/products/four-stroke-motorcycle-oils",
  },
  {
    src: "./navbar/2-stroke.webp",
    alt: "Two-Stroke Motorcycle & Engine Oils",
    title: "Two-Stroke Motorcycle & Engine Oils",
    link: "/products/two-stroke-motorcycle-and-engine-oils",
  },
  {
    src: "./navbar/marine.webp",
    alt: "Marine & Large Engine Oils",
    title: "Marine & Large Engine Oils",
    link: "/products/marine-and-large-engine-oils",
  },
  {
    src: "./navbar/gear.webp",
    alt: "Gear Oils",
    title: "Gear Oils",
    link: "/products/gear-oils",
  },
  {
    src: "./navbar/transmission.webp",
    alt: "Transmission Fluids",
    title: "Transmission Fluids",
    link: "/products/transmission-fluids",
  },
  {
    src: "./navbar/industrial.webp",
    alt: "Industrial Oils",
    title: "Industrial Oils",
    link: "/products/industrial-oils",
  },
  {
    src: "./navbar/transformer.webp",
    alt: "Transformer & Electrical Oils",
    title: "Transformer & Electrical Oils",
    link: "/products/transformer-and-electrical-oils",
  },
  {
    src: "./navbar/specialty.webp",
    alt: "Specialty Oils",
    title: "Specialty Oils",
    link: "/products/specialty-oils",
  },
  {
    src: "./navbar/brake.webp",
    alt: "Brake Fluids",
    title: "Brake Fluids",
    link: "/products/brake-fluids",
  },
  {
    src: "./navbar/grease.webp",
    alt: "Greases",
    title: "Greases",
    link: "/products/greases",
  },
];
