export const productsIO = [
  {
    src: "./products/Hyrax-Drum.webp",
    alt: "Hyrax Hydra SPV",
    title: "Hyrax Hydra SPV",
    link: "#",
    description:
      "A premium quality, shear stable, multigrade, very high viscosity index ashless type antiwear hydraulic fluid specially formulated using premium quality base fluids and high performance ashless additives system to provide excellent low temperature fluidity, excellent demulsibility and defoaming characteristics, and exceptional anti-wear protection for high pressure vane and piston pumps.",
    grades: ["ISO VG 32", "ISO VG 46", "ISO VG 68", "ISO VG 100", "ISO VG 150"],
    pdsLink: "./products/industrial/Hyrax-Hydra-SPV.pdf",
  },
  {
    src: "./products/Hyrax-Drum.webp",
    alt: "Hyrax HVI Hydra",
    title: "Hyrax HVI Hydra",
    link: "#",
    description:
      "A premium quality, shear stable, multigrade, high viscosity index anti-wear hydraulic fluid formulated using high quality base stocks and specially selected additives system to provide excellent low temperature fluidity, excellent demulsibility and defoaming characteristics, and exceptional anti-wear protection for high pressure vane and piston pumps.",
    grades: [
      "ISO VG 15",
      "ISO VG 22",
      "ISO VG 32",
      "ISO VG 46",
      "ISO VG 68",
      "ISO VG 80*",
      "ISO VG 100",
      "ISO VG 150",
    ],
    pdsLink: "./products/industrial/Hyrax-HVI-Hydra.pdf",
  },
  {
    src: "./products/Hyrax-Drum.webp",
    alt: "Hyrax HLP FZ",
    title: "Hyrax HLP FZ",
    link: "#",
    description:
      "A range of premium quality zinc-free anti-wear (AW) type hydraulic fluids manufactured with high quality base stocks and premium ashless additives technology primarily designed for used in hydraulic system in industrial and mobile application which requires heavy-duty, anti-wear hydraulic fluids with excellent water separating characteristics.",
    grades: [
      "ISO VG 10",
      "ISO VG 22",
      "ISO VG 32",
      "ISO VG 46",
      "ISO VG 68",
      "ISO VG 80*",
      "ISO VG 100",
    ],
    pdsLink: "./products/industrial/Hyrax-HLP-FZ.pdf",
  },
  {
    src: "./products/Hyrax-Drum.webp",
    alt: "Hyrax HLP",
    title: "Hyrax HLP",
    link: "#",
    description:
      "A range of premium quality anti-wear (AW) type hydraulic fluids manufactured with high quality base stocks and premium additives system primarily designed for used in hydraulic system in industrial and mobile application which requires heavy-duty, anti-wear hydraulic fluids with excellent water separating characteristics.",
    grades: [
      "ISO VG 10",
      "ISO VG 15",
      "ISO VG 22",
      "ISO VG 32",
      "ISO VG 46",
      "ISO VG 68",
      "ISO VG 100",
      "ISO VG 150",
    ],
    pdsLink: "./products/industrial/Hyrax-HLP.pdf",
  },
  {
    src: "./products/Hyrax-Drum.webp",
    alt: "Hyrax HLP VG 10W",
    title: "Hyrax HLP VG 10W",
    link: "#",
    description:
      "A specially formulated premium quality anti-wear (AW) type hydraulic fluids manufactured with high quality base stocks and premium additives system primarily designed for used in hydraulic system in industrial and mobile application (on-road and off-road) which requires heavyduty and anti-wear hydraulic fluid.",
    grades: ["ISO VG 10W"],
    pdsLink: "./products/industrial/Hyrax-HLP-VG-10W.pdf",
  },
  {
    src: "./products/Hyrax-Drum.webp",
    alt: "Hyrax HL",
    title: "Hyrax HL",
    link: "#",
    description:
      "A range of high quality anti Rust and Oxidation (R&O) type hydraulic fluids blended from high quality base stocks and selected additives system to provide excellent thermal and oxidation stability and excellent water separating characteristics.",
    grades: ["ISO VG 32", "ISO VG 46", "ISO VG 68", "ISO VG 100"],
    pdsLink: "./products/industrial/Hyrax-HL.pdf",
  },
  {
    src: "./products/Hyrax-Drum.webp",
    alt: "Hyrax Tundra HT",
    title: "Hyrax Tundra HT",
    link: "#",
    description:
      "A premium quality extended service life zinc-free turbine oil made of highly refined base stocks and specially selected ashless additive system for the lubrication of steam, hydroelectric and frame type gas turbines.",
    grades: ["ISO VG 32", "ISO VG 46", "ISO VG 68", "ISO VG 80*"],
    pdsLink: "./products/industrial/Hyrax-Tundra-HT.pdf",
  },
  {
    src: "./products/Hyrax-Drum.webp",
    alt: "Hyrax Tundra EP",
    title: "Hyrax Tundra EP",
    link: "#",
    description:
      "A premium quality extended service life anti-wear turbine oil specially made of highly refined base stocks and high performance additive system for the severe lubrication of steam, hydroelectric and frame type gas turbines.",
    grades: ["ISO VG 32", "ISO VG 46", "ISO VG 68", "ISO VG 80*", "ISO VG 100"],
    pdsLink: "./products/industrial/Hyrax-Tundra-EP.pdf",
  },
  {
    src: "./products/Hyrax-Drum.webp",
    alt: "Hyrax Compro Syn FLS",
    title: "Hyrax Compro Syn FLS",
    link: "#",
    description:
      "A long-life Diester air compressor oil specially designed for high temperature application and provide long-term lubrication with minimal deposit formations.",
    grades: ["ISO VG 46", "ISO VG 68"],
    pdsLink: "./products/industrial/Hyrax-Compro-Syn-FLS.pdf",
  },
  {
    src: "./products/Hyrax-Drum.webp",
    alt: "Hyrax Compro XS",
    title: "Hyrax Compro XS",
    link: "#",
    description:
      "A specially formulated extended service oil designed for the lubrication of rotary sliding vane and screw air compressors.",
    grades: ["ISO VG 32", "ISO VG 46", "ISO VG 68", "ISO VG 100"],
    pdsLink: "./products/industrial/Hyrax-Compro-XS.pdf",
  },
  {
    src: "./products/Hyrax-Drum.webp",
    alt: "Hyrax Compro",
    title: "Hyrax Compro",
    link: "#",
    description:
      "Designed for the lubrication of rotary sliding vane and screw air compressors.",
    grades: [
      "ISO VG 32",
      "ISO VG 46",
      "ISO VG 68",
      "ISO VG 100",
      "ISO VG 150",
      "ISO VG 220",
    ],
    pdsLink: "./products/industrial/Hyrax-Compro.pdf",
  },
  {
    src: "./products/Hyrax-Drum.webp",
    alt: "Hyrax Extol Syn HFC",
    title: "Hyrax Extol Syn HFC",
    link: "#",
    description:
      "A polyol ester based synthetic refrigeration compressor oil specially designed for use with HFC refrigerants and refrigerant blends (R134A, R23, R404A, R407C, R507) for standard factory fill of air conditioning and industrial refrigeration equipment.",
    grades: ["ISO VG 32", "ISO VG 46", "ISO VG 68", "ISO VG 120", "ISO VG 170"],
    pdsLink: "./products/industrial/Hyrax-Extol-Syn-HFC.pdf",
  },
  {
    src: "./products/Hyrax-Drum.webp",
    alt: "Hyrax Extol Syn FC",
    title: "Hyrax Extol Syn FC",
    link: "#",
    description:
      "An alkyl benzene based synthetic refrigeration compressor oil designed for used in applications such as R-502 and low temperature R-22 where improve miscibility is required.",
    grades: ["ISO VG 32", "ISO VG 68", "ISO VG 100"],
    pdsLink: "./products/industrial/Hyrax-Extol-Syn-FC.pdf",
  },
  {
    src: "./products/Hyrax-Drum.webp",
    alt: "Hyrax Extol",
    title: "Hyrax Extol",
    link: "#",
    description:
      "A specially formulated refrigeration compressor oil using carefully selected high quality naphthenic base oils and additive packages to provide superior low temperature performance as well as chemical stability and compatibility.",
    grades: ["ISO VG 32", "ISO VG 46", "ISO VG 68", "ISO VG 100"],
    pdsLink: "./products/industrial/Hyrax-Extol.pdf",
  },
];
